<?php

namespace App\Services\Common\Api;

use Illuminate\Routing\Redirector;
use Illuminate\Contracts\View\Factory as ViewFactory;
use Illuminate\Routing\ResponseFactory;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\ValidationException;
use PiApp\Exceptions\BaseException;

class ApiResponse extends ResponseFactory
{
    private $returnCode    = '0000';
    private $returnMessage = 'success';

    public function __construct(ViewFactory $view, Redirector $redirector)
    {
        parent::__construct($view, $redirector);
    }

    public function json($data = [], $status = 200, array $headers = [], $options = 0)
    {
        $resHeader = [
            'code'    => $this->returnCode,
            'message' => $this->returnMessage
        ];

        $data = [
            'data' => $data
        ];
        $data = array_merge($resHeader, $data);
        Log::info('輸出參數 ' . json_encode($data, JSON_UNESCAPED_UNICODE));

        return parent::json($data, $status, $headers, $options); // TODO: Change the autogenerated stub
    }

    public function exception(\Throwable $e, $optionalData = [])
    {
        // 為縮短Log長度
        // 分開記log
        Log::error(get_class($e));
        Log::error($e->getMessage());
        Log::error($e->getFile() . ':' . $e->getLine());
        Log::error($e);

        $code = $e->getCode();
        $code = $code === 0 ? '500' : $code;
        $data = [
            'code'    => (string)$code,
            'message' => '伺服器忙碌中，請重新操作或聯絡客服'
        ];

        if ($e instanceof BaseException) {
            $data['message'] = $e->getMessage();
        }

        if ($e instanceof ValidationException) {
            $data['code']    = (string)$e->status;
            $data['message'] = $e->validator->errors()->first();
        }

        if (count($optionalData) !== 0) {
            $data['data'] = $optionalData;
        }

        if (Config::get('app.debug')) {
            $data['data']['debug'] = [
                'message'       => $e->getMessage(),
                'debug_message' => $e instanceof BaseException ? $e->getDebugMessage() : '',
            ];
        }

        return parent::json($data, 200, [], 0);
    }

    public function success(): Response
    {
        $this->returnCode    = '0000';
        $this->returnMessage = 'success';

        return $this;
    }

    public function failed($failedCode = 403, $failedMessage = 'failed'): Response
    {
        $this->returnCode    = $failedCode;
        $this->returnMessage = $failedMessage;

        return $this;
    }
}
